# Generated by Django 5.1.2 on 2024-11-12 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctor',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='locale',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='translation_key',
        ),
    ]
